#!/usr/bin/env node
'use strict'

const bluebird = require('bluebird')
const co       = require('co')
const log      = require('fancy-log')
const moment   = require('moment-timezone')
const redis    = require('redis')

const grass    = require('../../../lib/grass')
const Slack    = require('../../../lib/slack')

bluebird.promisifyAll(redis.RedisClient.prototype)
bluebird.promisifyAll(redis.Multi.prototype)

// ----------------------------------------------------------------------------

const isProduction = !!process.env.OPENSHIFT_APP_NAME

const client = redis.createClient(isProduction ? {
  host    : process.env.OPENSHIFT_REDIS_HOST,
  port    : process.env.OPENSHIFT_REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
} : {})

// ----------------------------------------------------------------------------

const githubUsername = process.env.GITHUB_USERNAME

const slack = new Slack({
  token  : process.env.SLACK_API_TOKEN,
  channel: process.env.SLACK_CHANNEL,
  user   : {
    username: process.env.SLACK_USERNAME || 'izetta',
    icon_url: process.env.SLACK_ICON_URL || '',
  },
  message: process.env.SLACK_MESSAGE,
})

// ----------------------------------------------------------------------------

const notifyTimeZone = process.env.NOTIFY_TIMEZONE || 'Asia/Tokyo'
const notifyTimes    = []
const now            = moment.tz(notifyTimeZone)

if (process.env.NOTIFY_TIMES) {
  const times = process.env.NOTIFY_TIMES.split(',')
  times.forEach(time => {
    const [ hours, minutes ] = time.split(':')
    const tmp = moment.tz(notifyTimeZone)
      .hours(hours)
      .minutes(minutes)

    if (tmp.isValid()) {
      notifyTimes.push(tmp)

      const yesterday = tmp.clone().subtract(1, 'day')
      if (now.diff(yesterday, 'hours') < 12) {
        notifyTimes.push(yesterday)
      }
    }
  })
  notifyTimes.sort((a, b) => b.diff(a)) // order by desc
}

// ----------------------------------------------------------------------------

co(function* () {
  log(slack.message)
  for (const time of notifyTimes) {
    const key  = time.format('YYYY-MM-DD_HH:mm')
    const done = yield client.getAsync(key)

    if (done) { break }
    if (now.diff(time) > 0) {
      log('Checking GitHub grasses ... ')
      yield client.setAsync(key, 1) // marked

      if (grass.isWithered(time, githubUsername)) {
        log('GitHub lush grassess is withered!')
        yield slack.notifyWithered()
      }

      break // skip
    }
  }
})
  .then(
    ()  => process.exit(0),
    err => {
      console.error(err)
      process.exit(1)
    }
  )

// vim: se et ts=2 sw=2 sts=2 ft=javascript :
